export const BARANGAYS = [
    'Burol_I', 'Burol_II', 'Burol_III', 'Burol_Main',
    'Datu_Esmael', 'Emannuel_Bergado_I', 'Emannuel_Bergado_II',
    'Fatima_I', 'Fatima_II', 'Fatima_III', 'H2',
    'Langkaan_I', 'Langkaan_II',
    'Luzviminda_I', 'Luzviminda_II',
    'Paliparan_I', 'Paliparan_II', 'Paliparan_III',
    'Sabang', 'Salawag',
    'Salitran_I', 'Salitran_II', 'Salitran_III', 'Salitran_IV',
    'Sampaloc_I', 'Sampaloc_II', 'Sampaloc_III', 'Sampaloc_IV', 'Sampaloc_V',
    'San_Agustin_I', 'San_Agustin_II', 'San_Agustin_III',
    'San_Andres_I', 'San_Andres_II',
    'San_Antonio_De_Padua_I', 'San_Antonio_De_Padua_II',
    'San_Dionisio', 'San_Francisco_I',
    'San_IL_I', 'San_IL_II',
    'San_Jose', 'San_Juan',
    'San_Lorenzo_Ruis_I', 'San_Lorenzo_Ruis_II',
    'San_Luis_I', 'San_Luis_II',
    'San_Manuel_I', 'San_Manuel_II',
    'San_Mateo', 'San_Miguel_I', 'San_Miguel_II',
    'San_Nicholas_I', 'San_Nicholas_II',
    'San_Roque', 'San_Simon',
    'Santa_Cristina_I', 'Santa_Cristina_II',
    'Santa_Cruz_I', 'Santa_Cruz_II', 'Santa_Fe',
    'Santa_Lucia', 'Santa_Maria',
    'Santo_Cristo', 'Santo_Estoban',
    'Santo_Nino_I', 'Santo_Nino_II',
    'Santo_Peter_I', 'Santo_Peter_II',
    'Victoria_Reyes',
    'Zone_I', 'Zone_IA', 'Zone_II', 'Zone_III', 'Zone_IV',
  ]