import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { Button } from '@/components/ui/button'
import { Checkbox } from "@/components/ui/checkbox"
import { useState, useEffect} from "react"
import { toast } from "sonner"

export default function Terms() {
    const [ checked, setChecked ] = useState(false)
    const [ open, setOpen ] = useState(!checked)


    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogContent 
            onInteractOutside={(e) => e.preventDefault()}
            onEscapeKeyDown={(e) => e.preventDefault()}
            className="grid grid-cols-1 bg-[#1D2129] text-white h-[70vh] lg:h-[80vh] overflow-hidden">
            <div className="grid grid-cols-1 col-span-1 overflow-y-auto gap-3">
            <DialogHeader className="grid grid-cols-1 col-span-1 justify-center">
                <DialogTitle className="col-span-1 justify-self-center">Terms and Conditions</DialogTitle>
                <DialogDescription className="col-span-1 justify-self-center">Refer to the Information Below</DialogDescription>
            </DialogHeader>
                <Label className="cols-span-1">
                    By accessing and using this system, you agree to the following terms:
                </Label>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
<li>The system is provided for research and academic purposes only.</li>

<li>Data displayed or generated by the system may not be fully accurate and should not be used as the sole basis for critical decisions.</li>

<li>Users are expected to use the system responsibly and avoid any misuse that may compromise its functionality or purpose.</li>

<li>The project team and institution are not liable for any damages, losses, or misinterpretations resulting from the use of this system.</li>
                </ul>
                <Separator className="col-span-1"/>
                <div className="flex items-start gap-3 col-span-1">
                    <Checkbox id="terms-2" checked={checked} onCheckedChange={(v) => setChecked(v === true)} required/>
                    <div className="grid gap-2">
                    <Label htmlFor="terms-2">Accept terms and conditions</Label>
                    <p className="text-muted-foreground text-sm">
                        By clicking this checkbox, you agree to the terms and conditions.
                    </p>
                    </div>
                </div>
                <Button 
                    onClick={() => {
                        checked ? setOpen(false) : toast("Please Agree to Terms & Conditions")
                    }}
                    className="w-[40%] justify-self-center"
                >
                    Continue
                </Button>
                <DialogFooter className="grid justify-self-center">
                    <Label className="justify-self-center font-[Formula]">D A S M A - P</Label>
                </DialogFooter>
            </div>
            </DialogContent>
        </Dialog>
    )
}